name: rejector
channels:
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pip:
      - pyflakes=2.4.0
      - autopep8=1.6.0
      - numpy=1.21.3
      - matplotlib=3.4.3
      - sklearn=0.0
      - scipy=1.7.1
      - tqdm=4.62.3
