name: smart-rejector
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.5
  - libpython
  - pip
  - pip:
      - pyflakes==2.4.0
      - black==22.6.0
      - numpy==1.22.4
      - ipykernel==6.9.1  
      # The packages below are required for the rejector
      - matplotlib==3.4.3
      - sklearn==0.0
      - scipy==1.7.1
      - statsmodels==0.13.2

      # The packages below are required for content-analysis
      - gensim==4.2.0
      - scikit-learn==1.0.2

      # The packages below are required for the cost analysis
      - seaborn==0.11.2
      - krippendorff==0.5.1
      - ipympl==0.9.1
      - pandas==1.3.5

      # The packages below are required for the models but already
      # included in the notebooks since we trained the models
      # on Google Colab.
      - h5py=3.1.0
      - tensorflow
      - transformers==4.20.1
      - torch==4.1.1
      - datasets==2.3.2
      - tweet-preprocessor==0.6.0
      - tensorflow_probability
      - wordsegment==1.3.1