name: smart-rejector
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.5
  - libpython
  - pip
  - pip:
      # The packages below are required for the model
      - scikit-learn==1.0.2
      - spacy==3.2.1
      - tqdm==4.62.3
      # Use specific keras and tensorflow 2.7.0 version to include a bug fix
      # For saving the model with a TextVectorization layer.
      - keras==2.7.0rc0
      - tensorflow==2.7.0rc0
      - tensorflow-gpu==2.7.0rc0
      - tflearn==0.5.0
      - h5py==3.1.0
      - tensorflow-probability==0.15.0
      - pandas==1.3.5

      # The packages below are required for the rejector
      - pyflakes==2.4.0
      - autopep8==1.6.0
      - matplotlib==3.4.3
      - sklearn==0.0
      - scipy==1.7.1
      - statsmodels==0.13.2

      # The packages below are required for both
      - tqdm==4.62.3
      - numpy==1.19.2
      - ipykernel==6.9.1

      # The packages below are required for content-analysis
      - gensim==4.2.0

      # The packages below are required for the cost analysis
      - seaborn==0.11.2
      - krippendorff==0.5.1
