name: cnn
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.5
  - libpython
  - pip:
      - scikit-learn==1.0.2
      - spacy==3.2.1
      - tqdm==4.62.3
      - numpy==1.21.5
      # Use specific keras and tensorflow 2.7.0 version to include a bug fix
      # For saving the model with a TextVectorization layer.
      - keras==2.7.0rc0
      - tensorflow==2.7.0rc0
      - tensorflow-gpu==2.7.0
      - tflearn==0.5.0
      - h5py==3.6.0
      - tensorflow-probability==0.15.0
      - pandas==1.3.5
